### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-remote#16]
When I'm `yarn install`ing the [node-advanced boilerplate](https://github.com/graphql-boilerplates/node-graphql-server), I get this error message:

> warning "graphql-schema-cache@0.3.2" has incorrect peer dependency "graphql@^0.8.0".

In the `master` branch, `graphql` is already updated to `^0.12.3`, so I figure a new version should be released.

**Comment by schickling** [comment]
Should be fixed shortly.
