### ISSUE TITLE
Shouldn't create a new schema per request

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-remote#5]
As mentioned in #4 creating a new remote schema is expensive and shouldn't be done on a per request basis (or at least should be implemented more efficiently).

**Comment by kbrandwijk** [comment]
I'm caching the introspection schema result, the overhead of creating the actual schema from it is minimal, the introspection query takes most of the effort:
https://github.com/qewl/qewl/blob/master/src/middlewares/remoteSchema.ts#L68-L75
