### ISSUE TITLE
Link Switching has side effects

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphql-remote#8]
The latest version of `graphql-remote` caches schema instances and just replaces the pointer to the current link. This can have unwanted side effects.
As we assume, that each request to the underlying remote GraphQL API has the same context,
we can disregard this right now.
But you can hit the use case that this behavior is not wanted.
I write it down for documentation reasons, we may want to tackle this in the future by not just changing the "pointer" to the link, but actually creating new immutable schemas.

**Comment by schickling** [comment]
This issue was moved to graphcool/graphql-remote#2
